// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Use TURSO_DATABASE_URL for production (Turso), DATABASE_URL for local SQLite
    url: process.env["TURSO_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
