// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function resolveDatabaseUrl() {
  const url = process.env["TURSO_DATABASE_URL"] || process.env["DATABASE_URL"] || "file:./dev.db";
  if (url.startsWith('libsql:') || url.startsWith('file:') || url.startsWith('postgresql:') || url.startsWith('mysql:')) {
    return url;
  }
  return `file:${url}`;
}

const databaseUrl = resolveDatabaseUrl();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
