import prisma from '@/lib/prisma'
import { PDFDocument, rgb, StandardFonts, PDFPage, PDFFont } from 'pdf-lib'

export type ReportLanguage = 'fr' | 'en'

export interface ReportData {
  restaurantName: string
  month: number
  year: number
  language: ReportLanguage
  totalRevenue: number
  totalOrders: number
  averageOrderValue: number
  paidOrders: number
  cancelledOrders: number
  topDishes: { name: string; count: number; revenue: number }[]
  topTables: { number: string; orderCount: number; revenue: number }[]
  dailyBreakdown: { day: number; orders: number; revenue: number }[]
  generatedAt: string
}

// ──────────────────────────────────────────────
// I18N strings
// ──────────────────────────────────────────────
const STRINGS = {
  fr: {
    reportTitle: 'Rapport Mensuel',
    generatedOn: 'Généré le',
    period: 'Période',
    summary: 'Résumé du Mois',
    totalRevenue: 'Chiffre d\'Affaires',
    totalOrders: 'Commandes Totales',
    avgOrder: 'Panier Moyen',
    paidOrders: 'Commandes Payées',
    topDishes: 'Plats les Plus Vendus',
    topTables: 'Tables les Plus Actives',
    dailyBreakdown: 'Activité Journalière',
    dish: 'Plat',
    sold: 'Vendus',
    revenue: 'Revenus',
    table: 'Table',
    orders: 'Commandes',
    day: 'Jour',
    noOrders: 'Aucune commande ce mois-ci.',
    months: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    footer: 'Rapport généré automatiquement par FirstStep',
    restaurant: 'Restaurant',
    currency: 'MAD',
  },
  en: {
    reportTitle: 'Monthly Report',
    generatedOn: 'Generated on',
    period: 'Period',
    summary: 'Monthly Summary',
    totalRevenue: 'Total Revenue',
    totalOrders: 'Total Orders',
    avgOrder: 'Avg. Order Value',
    paidOrders: 'Paid Orders',
    topDishes: 'Top Selling Dishes',
    topTables: 'Most Active Tables',
    dailyBreakdown: 'Daily Activity',
    dish: 'Dish',
    sold: 'Sold',
    revenue: 'Revenue',
    table: 'Table',
    orders: 'Orders',
    day: 'Day',
    noOrders: 'No orders this month.',
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    footer: 'Report automatically generated by FirstStep',
    restaurant: 'Restaurant',
    currency: 'MAD',
  },
}

// ──────────────────────────────────────────────
// Analytics computation
// ──────────────────────────────────────────────
export async function computeMonthlyAnalytics(
  tenantId: string,
  month: number,
  year: number,
  restaurantName: string,
  language: ReportLanguage = 'fr'
): Promise<ReportData> {
  const startDate = new Date(year, month - 1, 1)
  const endDate = new Date(year, month, 0, 23, 59, 59, 999)

  const orders = await prisma.restaurantOrder.findMany({
    where: {
      table: { tenantId },
      createdAt: { gte: startDate, lte: endDate },
      // Exclude CALL WAITER dummy orders
      NOT: { items: { some: { name: '🔔 CALL WAITER' } } },
    },
    include: {
      items: true,
      table: { select: { number: true } },
    },
  })

  const totalOrders = orders.length
  const totalRevenue = orders.reduce((sum, o) => sum + o.totalAmount, 0)
  const paidOrders = orders.filter(o => o.status === 'PAID' || o.status === 'COMPLETED').length
  const averageOrderValue = totalOrders > 0 ? totalRevenue / totalOrders : 0

  // Top dishes
  const dishMap = new Map<string, { count: number; revenue: number }>()
  for (const order of orders) {
    for (const item of order.items) {
      const existing = dishMap.get(item.name) || { count: 0, revenue: 0 }
      dishMap.set(item.name, {
        count: existing.count + item.quantity,
        revenue: existing.revenue + item.price * item.quantity,
      })
    }
  }
  const topDishes = Array.from(dishMap.entries())
    .map(([name, v]) => ({ name, ...v }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 8)

  // Top tables
  const tableMap = new Map<string, { orderCount: number; revenue: number }>()
  for (const order of orders) {
    const num = order.table.number
    const existing = tableMap.get(num) || { orderCount: 0, revenue: 0 }
    tableMap.set(num, {
      orderCount: existing.orderCount + 1,
      revenue: existing.revenue + order.totalAmount,
    })
  }
  const topTables = Array.from(tableMap.entries())
    .map(([number, v]) => ({ number, ...v }))
    .sort((a, b) => b.orderCount - a.orderCount)
    .slice(0, 8)

  // Daily breakdown
  const daysInMonth = new Date(year, month, 0).getDate()
  const dailyBreakdown = Array.from({ length: daysInMonth }, (_, i) => {
    const day = i + 1
    const dayOrders = orders.filter(o => new Date(o.createdAt).getDate() === day)
    return {
      day,
      orders: dayOrders.length,
      revenue: dayOrders.reduce((s, o) => s + o.totalAmount, 0),
    }
  })

  return {
    restaurantName,
    month,
    year,
    language,
    totalRevenue,
    totalOrders,
    averageOrderValue,
    paidOrders,
    cancelledOrders: 0,
    topDishes,
    topTables,
    dailyBreakdown,
    generatedAt: new Date().toISOString(),
  }
}

// ──────────────────────────────────────────────
// PDF generation helpers
// ──────────────────────────────────────────────
function hexToRgb(hex: string) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  return result
    ? rgb(parseInt(result[1], 16) / 255, parseInt(result[2], 16) / 255, parseInt(result[3], 16) / 255)
    : rgb(0, 0, 0)
}

const BRAND_BLUE = hexToRgb('#2563eb')
const BRAND_DARK = hexToRgb('#111827')
const GRAY = hexToRgb('#6b7280')
const LIGHT_GRAY = hexToRgb('#f3f4f6')
const WHITE = rgb(1, 1, 1)
const GREEN = hexToRgb('#059669')
const BORDER = hexToRgb('#e5e7eb')

function drawRect(page: PDFPage, x: number, y: number, w: number, h: number, color: ReturnType<typeof rgb>) {
  page.drawRectangle({ x, y, width: w, height: h, color })
}

function drawLine(page: PDFPage, x1: number, y1: number, x2: number, y2: number) {
  page.drawLine({ start: { x: x1, y: y1 }, end: { x: x2, y: y2 }, thickness: 0.5, color: BORDER })
}

function drawText(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  font: PDFFont,
  size: number,
  color: ReturnType<typeof rgb> = BRAND_DARK
) {
  page.drawText(text, { x, y, size, font, color })
}

// ──────────────────────────────────────────────
// Main PDF builder
// ──────────────────────────────────────────────
export async function generateReportPdf(data: ReportData): Promise<Uint8Array> {
  const t = STRINGS[data.language]
  const fmt = (n: number) => `${n.toFixed(0)} ${t.currency}`
  const fmtDec = (n: number) => `${n.toFixed(2)} ${t.currency}`

  const pdfDoc = await PDFDocument.create()
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

  // ── PAGE 1: COVER + SUMMARY ──────────────────
  const page1 = pdfDoc.addPage([595, 842]) // A4
  const { width, height } = page1.getSize()

  // Header band
  drawRect(page1, 0, height - 120, width, 120, BRAND_DARK)
  drawText(page1, 'FIRSTSTEP', 40, height - 48, boldFont, 22, WHITE)
  drawText(page1, data.restaurantName.toUpperCase(), 40, height - 72, boldFont, 14, hexToRgb('#93c5fd'))
  drawText(page1, `${t.reportTitle} — ${t.months[data.month - 1]} ${data.year}`, 40, height - 95, regularFont, 10, hexToRgb('#cbd5e1'))
  drawText(page1, `${t.generatedOn}: ${new Date(data.generatedAt).toLocaleDateString(data.language === 'fr' ? 'fr-FR' : 'en-US')}`, width - 220, height - 95, regularFont, 9, hexToRgb('#94a3b8'))

  // Blue accent bar
  drawRect(page1, 0, height - 124, width, 4, BRAND_BLUE)

  // ── Summary cards (4 KPI boxes) ──────────────
  const cardY = height - 200
  const cardH = 72
  const cardW = (width - 80 - 18) / 4
  const kpis = [
    { label: t.totalRevenue, value: fmt(data.totalRevenue), sub: '' },
    { label: t.totalOrders, value: `${data.totalOrders}`, sub: '' },
    { label: t.avgOrder, value: fmtDec(data.averageOrderValue), sub: '' },
    { label: t.paidOrders, value: `${data.paidOrders}`, sub: '' },
  ]
  kpis.forEach((k, i) => {
    const x = 40 + i * (cardW + 6)
    drawRect(page1, x, cardY, cardW, cardH, LIGHT_GRAY)
    drawText(page1, k.label, x + 10, cardY + cardH - 18, boldFont, 7, GRAY)
    drawText(page1, k.value, x + 10, cardY + cardH - 44, boldFont, 16, BRAND_DARK)
  })

  // ── Top Dishes table ─────────────────────────
  const section1Y = cardY - 40
  drawText(page1, t.topDishes, 40, section1Y, boldFont, 12, BRAND_DARK)
  drawRect(page1, 40, section1Y - 6, width - 80, 1, BRAND_BLUE)

  // Table header
  const col1 = 40, col2 = 280, col3 = 380, col4 = 470
  drawRect(page1, 40, section1Y - 28, width - 80, 18, hexToRgb('#eff6ff'))
  drawText(page1, t.dish, col1 + 4, section1Y - 22, boldFont, 8, GRAY)
  drawText(page1, t.sold, col2, section1Y - 22, boldFont, 8, GRAY)
  drawText(page1, t.revenue, col3, section1Y - 22, boldFont, 8, GRAY)

  let rowY = section1Y - 48
  if (data.topDishes.length === 0) {
    drawText(page1, t.noOrders, col1 + 4, rowY, regularFont, 9, GRAY)
  } else {
    data.topDishes.slice(0, 6).forEach((dish, idx) => {
      if (idx % 2 === 0) drawRect(page1, 40, rowY - 4, width - 80, 16, LIGHT_GRAY)
      drawText(page1, dish.name.slice(0, 38), col1 + 4, rowY, regularFont, 9, BRAND_DARK)
      drawText(page1, `${dish.count}`, col2, rowY, regularFont, 9, BRAND_DARK)
      drawText(page1, fmt(dish.revenue), col3, rowY, regularFont, 9, GREEN)
      rowY -= 18
    })
  }

  // ── Top Tables ───────────────────────────────
  const section2Y = rowY - 24
  drawText(page1, t.topTables, 40, section2Y, boldFont, 12, BRAND_DARK)
  drawRect(page1, 40, section2Y - 6, width - 80, 1, BRAND_BLUE)
  drawRect(page1, 40, section2Y - 28, width - 80, 18, hexToRgb('#eff6ff'))
  drawText(page1, t.table, col1 + 4, section2Y - 22, boldFont, 8, GRAY)
  drawText(page1, t.orders, col2, section2Y - 22, boldFont, 8, GRAY)
  drawText(page1, t.revenue, col3, section2Y - 22, boldFont, 8, GRAY)

  let rowY2 = section2Y - 48
  if (data.topTables.length === 0) {
    drawText(page1, t.noOrders, col1 + 4, rowY2, regularFont, 9, GRAY)
  } else {
    data.topTables.slice(0, 6).forEach((tbl, idx) => {
      if (idx % 2 === 0) drawRect(page1, 40, rowY2 - 4, width - 80, 16, LIGHT_GRAY)
      drawText(page1, `Table ${tbl.number}`, col1 + 4, rowY2, regularFont, 9, BRAND_DARK)
      drawText(page1, `${tbl.orderCount}`, col2, rowY2, regularFont, 9, BRAND_DARK)
      drawText(page1, fmt(tbl.revenue), col3, rowY2, regularFont, 9, GREEN)
      rowY2 -= 18
    })
  }

  // ── Footer page 1 ────────────────────────────
  drawRect(page1, 0, 0, width, 36, BRAND_DARK)
  drawText(page1, t.footer, 40, 12, regularFont, 8, hexToRgb('#94a3b8'))
  drawText(page1, `1 / 2`, width - 60, 12, regularFont, 8, hexToRgb('#94a3b8'))

  // ── PAGE 2: DAILY ACTIVITY ────────────────────
  const page2 = pdfDoc.addPage([595, 842])

  // Header band
  drawRect(page2, 0, height - 120, width, 120, BRAND_DARK)
  drawText(page2, 'FIRSTSTEP', 40, height - 48, boldFont, 22, WHITE)
  drawText(page2, data.restaurantName.toUpperCase(), 40, height - 72, boldFont, 14, hexToRgb('#93c5fd'))
  drawText(page2, `${t.dailyBreakdown} — ${t.months[data.month - 1]} ${data.year}`, 40, height - 95, regularFont, 10, hexToRgb('#cbd5e1'))
  drawRect(page2, 0, height - 124, width, 4, BRAND_BLUE)

  // Daily table
  const dSec = height - 160
  drawText(page2, t.dailyBreakdown, 40, dSec, boldFont, 12, BRAND_DARK)
  drawRect(page2, 40, dSec - 6, width - 80, 1, BRAND_BLUE)

  // 3-column layout for days
  const days = data.dailyBreakdown
  const colW = (width - 80) / 3
  const dayH = 22
  const dayStartY = dSec - 32

  days.forEach((d, idx) => {
    const col = idx % 3
    const row = Math.floor(idx / 3)
    const x = 40 + col * colW
    const y = dayStartY - row * dayH

    if (idx % 2 === 0 && col === 0) {
      // Light row background across all 3 cols
    }

    const cellColor = d.orders > 0 ? LIGHT_GRAY : WHITE
    drawRect(page2, x + 2, y - 4, colW - 4, dayH - 2, cellColor)

    const dayLabel = `${String(d.day).padStart(2, '0')}/${String(data.month).padStart(2, '0')}`
    drawText(page2, dayLabel, x + 6, y + 4, boldFont, 8, GRAY)
    drawText(page2, `${d.orders} cmd`, x + colW * 0.38, y + 4, regularFont, 8, BRAND_DARK)
    drawText(page2, fmt(d.revenue), x + colW * 0.65, y + 4, regularFont, 8, GREEN)
  })

  // Mini bar chart for revenue
  const chartY = dayStartY - Math.ceil(days.length / 3) * dayH - 48
  drawText(page2, data.language === 'fr' ? 'Revenus par Jour' : 'Daily Revenue', 40, chartY, boldFont, 11, BRAND_DARK)
  drawRect(page2, 40, chartY - 6, width - 80, 1, BRAND_BLUE)

  const maxRev = Math.max(...days.map(d => d.revenue), 1)
  const barW = (width - 80) / days.length - 1.5
  const barMaxH = 80
  const barBaseY = chartY - 110

  days.forEach((d, idx) => {
    const barH = (d.revenue / maxRev) * barMaxH
    const x = 40 + idx * (barW + 1.5)
    if (d.revenue > 0) {
      drawRect(page2, x, barBaseY, barW, barH, BRAND_BLUE)
    }
    // Base line
    drawRect(page2, x, barBaseY - 1, barW, 1, BORDER)
  })
  // Axis
  drawLine(page2, 40, barBaseY - 2, width - 40, barBaseY - 2)

  // ── Footer page 2 ────────────────────────────
  drawRect(page2, 0, 0, width, 36, BRAND_DARK)
  drawText(page2, t.footer, 40, 12, regularFont, 8, hexToRgb('#94a3b8'))
  drawText(page2, `2 / 2`, width - 60, 12, regularFont, 8, hexToRgb('#94a3b8'))

  return await pdfDoc.save()
}
